# Generated by Django 3.0 on 2019-12-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20191217_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='departamentos',
            field=models.ManyToManyField(blank=True, to='clientes.Departamento'),
        ),
    ]
