# Generated by Django 3.0 on 2019-12-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_clientes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(upload_to='clintes_fotos'),
        ),
    ]
